year: 1975
source: '1975 Aquatic Programme, Bala Aquatic Association'

officials:
  - role: commodore
    name: Bob McAdam
  - role: vice-commodore
    titleAsPrinted: 1st Vice-Commodore
    name: John Anthony
  - role: second-vice-commodore
    titleAsPrinted: 2nd Vice-Commodore
    name: Norman Munn
  - role: rear-commodore
    name: Bud Smail
  - role: past-commodore
    name: John Butler
