year: 1977
source: '1977 Aquatic Programme, Bala Aquatic Association'

officials:
  - role: commodore
    name: John Anthony
    person: john-anthony
  - role: vice-commodore
    titleAsPrinted: 1st Vice-Commodore
    name: Norman Munn
    person: norman-munn
  - role: second-vice-commodore
    titleAsPrinted: 2nd Vice-Commodore
    name: Al Price
    person: al-price
  - role: rear-commodore
    name: Bud Smail
    person: bud-smail
  - role: past-commodore
    name: Bob McAdam
    person: bob-mcadam
